# Generated by Django 5.1.3 on 2024-11-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_medicine_stock_medicine_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Dosage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(default='OTC Medicine', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='store.category'),
        ),
    ]
