# Generated by Django 5.1.3 on 2024-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_medicine_dosage_alter_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='diseases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
